image: node:16

clone:
  lfs: true
  depth: 1

pipelines:
  pull-requests:
    "**":
      - step:
          name: Test & Build
          size: 2x
          caches:
            - node
          script:
            - npm ci --no-audit --no-progress
            - npm test -- --coverage
            - mv deploy/config/internal/.env.alpha ./.env
            - npm run build
      - step:
          name: Build Android APK
          size: 2x
          trigger: manual
          script:
            - docker build --build-arg SSH_PRIVATE_KEY=$BITBUCKET_PRIVATE_KEY -f BuildApp.Dockerfile -t cordovabuild .
            - docker create -ti --name cordovabuild cordovabuild bash
            - docker cp cordovabuild:/app/build ./
            - docker rm -f cordovabuild
          artifacts:
            - build/apk/debug/**
          services:
            - docker
          caches:
            - docker
  custom:
    deploy:
      - variables:
          - name: KIDSLOOP_REGION
          - name: KIDSLOOP_ENV
      - step:
          name: "Build NPM"
          image: node:lts
          script:
            - npm ci --no-audit --no-progress
            - mv deploy/config/$KIDSLOOP_REGION/.env.$KIDSLOOP_ENV ./.env
            - npm run build
          caches:
            - nodemodules
          artifacts:
            - dist/**

      - step:
          name: "Build & Push Docker image"
          image: python:3.9-alpine
          script:
            - pip3 install -U awscli
            - mv dist deploy/

            - export BRANCH_TAG=$(echo "$BITBUCKET_BRANCH" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')
            - export REPO=$DOCKER_REPO_URL/kidsloop-live-frontend # DOCKER_REPO_URL is workspace wide variable
            - export COMMIT_TAG=$(echo $BITBUCKET_COMMIT | cut -c1-7)
            - if test -z "$BRANCH_TAG"; then export TAG=commit-$KIDSLOOP_REGION-$KIDSLOOP_ENV; else export TAG=$BRANCH_TAG-$KIDSLOOP_REGION-$KIDSLOOP_ENV; fi
            - printf '"Git tag":"%s", "Git commit":"%s" "ECR repo":"%s"' $BRANCH_TAG $COMMIT_TAG $REPO

            - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL
            - docker build -t live-frontend deploy/

            - docker tag live-frontend:latest $REPO:$TAG
            - docker tag live-frontend:latest $REPO:$TAG-latest
            - docker tag live-frontend:latest $REPO:$TAG-$BITBUCKET_BUILD_NUMBER
            - docker tag live-frontend:latest $REPO:$TAG-$COMMIT_TAG

            - if test -n "$BRANCH_TAG"; then docker push $REPO:$TAG; fi
            - if test -n "$BRANCH_TAG"; then docker push $REPO:$TAG-latest; fi
            - docker push $REPO:$TAG-$BITBUCKET_BUILD_NUMBER
            - docker push $REPO:$TAG-$COMMIT_TAG

          services:
            - docker

definitions:
  caches:
    nodemodules: ./node_modules
