export const en = {
    activity_link: "Activity Link",
    button_activity: "Activity",
    button_camera_start: "Start",
    button_stop: "Stop",
    button_stream: "Stream",
    button_invite_students: "Invite",
    error_webrtc_unavailable: "Error: WebRTC context unavailable",
    error_unknown_content: "Error: Unknown content type",
    failed_to_connect: "Failed to connect",
    hello: "Hello, {name}!",
    open_preview_drawer: "Open Drawer",
    close_preview_drawer: "Close Drawer",
    start_activity_button: "Start Activity All",
    waiting_for_camera: "Waiting for camera permission",
    waiting_for_class: "Waiting for class to start.",
    waiting_for_students: "Waiting for students to join the room.",
    zoom_into_activity: "Zoom in this activity",
    live_buttonInteractiveLabel: "Interactive Modes",
    live_buttonStop: "Stop",
    live_buttonPresent: "Present",
    live_buttonActivity: "Student Mode",
    live_buttonEndClass: "End Class",
    student_stream_mode: "Your teacher is currently presenting",
    student_activity_mode: "Please follow your teacher's intruction",
};
