// en.ts
const messages: Record<string, string> = {
    activity_link: "Activity Link",
    allow_media_permission: "Please allow microphone and camera permissions if you want to use media devices.",
    error_camera_unavailable: "Can not access your 📷",
    error_empty_name: "Please enter your name.",
    error_invaild_token: "Invalid token could not connect to class.",
    error_webrtc_unavailable: "Error: WebRTC context unavailable",
    error_unknown_content: "Error: Unknown content type",
    error_unknown_error: "Oops! Something went wrong.",
    error_unknown_user: "Unknown user",
    failed_to_connect: "Failed to connect.",
    hello: "Hello, {name}!",
    waiting_for_class: "Waiting for class to start.",
    what_is_your_name: "What is your name?",
    loading: "Loading",
    loading_text: "Give us a sec while we get things ready!",
    student_stream_mode: "Your teacher is currently presenting.",
    student_activity_mode: "Please follow your teacher's intruction.",
    join_room: "Join Room",
    no_device_available: "No devices available",
    no_messages: "No messages yet...",
    no_participants: "No one has join the class yet...",
    select_device: "Select {device}",
    connect_camera: "Connect your 📷",

    refresh_activity: "Refresh Activity",
    what_is_this: "What is This?",
    live_buttonStop: "Show Webcam",
    live_buttonPresent: "Present",
    live_buttonObserve: "Observe",
    live_buttonScreen: "Share Screen",
    live_buttonStopFull: "Webcam Mode",
    live_buttonPresentFull: "Presenter Mode",
    live_buttonObserveFull: "Observation Mode",
    live_buttonScreenFull: "Share Screen",
    title_participants: "Participants",
    title_lesson_plan: "Lesson Plan",
    title_chat: "Chat",
    title_whiteboard: "Whiteboard",
    title_settings: "Settings",
    invite_students: "Invite",
    copy_clipboard: "Copied to clipboard!",
    quick_toggles: "Quick Toggles",
    set_cameras_off: "Set Cameras Off",
    set_cameras_on: "Set Cameras On",
    clear_whiteboard: "Clear Whiteboard",
    mute_all: "Mute All",
    unmute_all: "Unmute All",
    share_something_here: "Share something here",
    enable_dark_mode: "Enable dark mode",
    language: "Language",
    two_columns: "2 columns",
    four_columns: "4 columns",
    six_columns: "6 columns",
    num_views_per_row: "# of student views per row",

    whiteboard_color: "Color",
    whiteboard_clear: "Clear",
    whiteboard_hide: "Hide",
    whiteboard_show: "Show",

    turn_off_camera: "Turn off camera",
    turn_on_camera: "Turn on camera",
    turn_off_mic: "Turn off microphone",
    turn_on_mic: "Turn on microphone",

    browser_guide_title: "Kidsloop Live supports Chrome only.",
    browser_guide_title_ios: "Kidsloop Live supports Safari only on iOS.",
    browser_guide_body: "Please download {browserName} browser and try again.",

};
export default messages;