// vi.ts
const messages: Record<string, string> = {
    err_400_title: "Bad Request",
    err_400_description: "The server could not understand the request due to invalid syntax",
    err_401_title: "Unauthorized",
    err_401_description: "Please check if you are signed in",
    err_403_title: "Forbidden",
    err_403_description: "You don't have permission to access",
    err_404_title: "Not Found",
    err_404_description: "The requested URL was not found",
    err_500_title: "Internal Server Error",
    err_500_description: "Oops! Something went wrong",

    selectOrg_buttonSelect: "Select",

    activity_link: "Đường dẫn đến Hoạt động",
    allow_media_permission: "Nếu bạn muốn sử dụng các thiết bị truyền thông, vui lòng cho phép sử dụng micrô và máy ảnh của bạn.",
    error_camera_unavailable: "Không thể truy cập 📷",
    error_empty_name: "Vui lòng nhập tên.",
    error_invaild_token: "Không được cấp phép nên không thể tham gia lớp học.",
    error_webrtc_unavailable: "Lỗi: Không có ngữ cảnh WebRTC",
    error_unknown_content: "Lỗi: Loại nội dung không xác định",
    error_unknown_error: "Tiếc quá! Có lỗi xảy ra.",
    error_unknown_user: "Người dùng không xác định",
    failed_to_connect: "Kết nối thất bại.",
    hello: "Xin chào {name}!",
    waiting_for_class: "Chờ lớp học bắt đầu.",
    what_is_your_name: "Bạn tên gì?",
    loading: "Loading",
    loading_text: "Vui lòng chờ trong giây lát!",
    student_stream_mode: "Giáo viên của bạn đang trình bày.",
    student_activity_mode: "Vui lòng làm theo hướng dẫn của giáo viên.",
    join_room: "Vào lớp",
    no_device_available: "Không có thiết bị",
    no_messages: "Hiện tại chưa có thông tin...",
    no_participants: "No one has join the class yet...",
    select_device: "Chọn {device}",
    connect_camera: "Kết nối 📷",

    refresh_activity: "Làm mới Hoạt động",
    what_is_this: "Cái gì đây?",
    live_buttonStop: "Ngưng",
    live_buttonPresent: "Trình bày",
    live_buttonObserve: "Chế độ học sinh",
    live_buttonScreen: "Chia sẻ màn hình",
    live_buttonStopFull: "Webcam Mode",
    live_buttonPresentFull: "Presenter Mode",
    live_buttonObserveFull: "Observation Mode",
    live_buttonScreenFull: "Share Screen",
    title_participants: "Những người tham gia",
    title_lesson_plan: "Giáo án",
    title_chat: "Trò chuyện",
    title_whiteboard: "Bảng",
    title_settings: "Cài đặt",
    invite_students: "Mời",
    copy_clipboard: "Sao chép vào bảng tạm!",
    quick_toggles: "Chuyển đổi nhanh",
    set_cameras_off: "Tắt máy ảnh",
    set_cameras_on: "Bật máy ảnh",
    mute_all: "Tắt tiếng",
    unmute_all: "Bật tiếng",
    hide_whiteboard: "Hide Whiteboard",
    show_whiteboard: "Show Whiteboard",
    clear_whiteboard: "Clear Whiteboard",
    give_star: "Give Star to all",
    give_trophy: "Give Trophy to all",
    give_heart: "Give Heart to all",
    encourage: "Encourage to all",
    share_something_here: "Trò chuyện tại đây",
    enable_dark_mode: "Bật chế độ nền tối",
    language: "Ngôn ngữ",
    two_columns: "2 cột",
    three_columns: "3 cột",
    four_columns: "4 cột",
    six_columns: "6 cột",
    cols_camera_per_row: "# of cameras per row",
    cols_observe_per_row: "Số lượng màn hình học viên được hiển thị trên một hàng",

    whiteboard_color: "Màu",
    whiteboard_clear: "Xóa",
    whiteboard_hide: "Ẩn",
    whiteboard_show: "Hiện",

    turn_off_camera: "Turn off camera",
    turn_on_camera: "Turn on camera",
    turn_off_mic: "Turn off microphone",
    turn_on_mic: "Turn on microphone",

    browser_guide_title: "Kidsloop Live supports Chrome only.",
    browser_guide_title_macos: "Kidsloop Live supports Safari and Chrome only on Mac OS.",
    browser_guide_title_ios: "Kidsloop Live supports Safari only on iOS.",
    browser_guide_body: "Please download a supported browser and try again.",
};
export default messages;