// cn.ts
const messages: Record<string, string> = {
    err_400_title: "Bad Request",
    err_400_description: "The server could not understand the request due to invalid syntax",
    err_401_title: "Unauthorized",
    err_401_description: "Please check if you are signed in",
    err_403_title: "Forbidden",
    err_403_description: "You don't have permission to access",
    err_404_title: "Not Found",
    err_404_description: "The requested URL was not found",
    err_500_title: "Internal Server Error",
    err_500_description: "Oops! Something went wrong",

    activity_link: "活动链接",
    allow_media_permission: "如果您想要使用媒体设备，请授权允许使用你的话筒和相机",
    error_camera_unavailable: "📷摄像头无法访问",
    error_empty_name: "请输入你的名字",
    error_invaild_token: "没有权限无法上课",
    error_webrtc_unavailable: "错误：WebRTC 上下文不可用",
    error_unknown_content: "错误：未知内容类型",
    error_unknown_error: "对不起！发生了一些错误",
    error_unknown_user: "未知用户",
    failed_to_connect: "连接失败",
    hello: "你好，{name}！",
    waiting_for_class: "等待课程开始",
    what_is_your_name: "你叫什么名字",
    loading: "载入中",
    loading_text: "正在准备请稍等！",
    student_stream_mode: "老师目前正在上课",
    student_activity_mode: "请遵照老师的指示",
    join_room: "进入教室",
    no_device_available: "没有可用的设备",
    no_messages: "目前没有信息...",
    no_participants: "目前还没有人进入班级...",
    select_device: "选择{device}",
    connect_camera: "访问你的摄像头📷",

    refresh_activity: "刷新活动",
    what_is_this: "这是什么？",
    live_buttonStop: "停止",
    live_buttonPresent: "课程演示",
    live_buttonObserve: "学生模式",
    live_buttonScreen: "共享屏幕",
    live_buttonStopFull: "摄像头模式",
    live_buttonPresentFull: "演示模式",
    live_buttonObserveFull: "观察模式",
    live_buttonScreenFull: "共享屏幕",
    title_participants: "参加人员",
    title_lesson_plan: "教学计划",
    title_chat: "聊天",
    title_whiteboard: "白板",
    title_settings: "设置",
    invite_students: "邀请",
    copy_clipboard: "复制到剪贴板",
    quick_toggles: "快速操作",
    set_cameras_off: "设置摄像头关闭",
    set_cameras_on: "设置摄像头打开",
    mute_all: "全部静音",
    unmute_all: "解除静音",
    hide_whiteboard: "隐藏白板",
    show_whiteboard: "显示白板",
    clear_whiteboard: "清除白板",
    give_star: "给所有人星星",
    give_trophy: "给所有人奖杯",
    give_heart: "给所有人爱心",
    encourage: "给所有人鼓励",
    share_something_here: "上传你想分享的内容",
    enable_dark_mode: "使用深色模式",
    language: "语言",
    two_columns: "2列",
    three_columns: "3列",
    four_columns: "4列",
    six_columns: "6列",
    cols_camera_per_row: "一行中显示的摄像头数量",
    cols_observe_per_row: "一行中显示的学生屏幕数量",

    whiteboard_color: "颜色",
    whiteboard_clear: "清除",
    whiteboard_hide: "隐藏",
    whiteboard_show: "展示",

    turn_off_camera: "关闭摄像头",
    turn_on_camera: "打开摄像头",
    turn_off_mic: "关闭麦克风",
    turn_on_mic: "打开麦克风",

    browser_guide_title: "KidsLoop Live仅支持Chrome浏览器",
    browser_guide_title_macos: "KidsLoop Live在Mac OS系统中支持Safari 和Chrome 浏览器",
    browser_guide_title_ios: "KidsLoop Live在iOS系统中仅支持Safari浏览器",
    browser_guide_body: "请下载支持的浏览器并重试",

};
export default messages;