fastlane_require 'dotenv'
default_platform(:ios)
platform :ios do
  before_all do
    Dotenv.overload('.env', '.env.secret')
  end

  desc "Sync signing"
  lane :signing do
    match(type: "development", readonly: is_ci)

    mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end
  desc "build ios app"
  lane :build do
    signing
    build_ios_app
  end
  desc "publish"
  lane :publish do
    build
  end

end
