fastlane_require 'dotenv'
default_platform(:ios)
platform :ios do
  before_all do
    Dotenv.overload('.env', '.env.secret')
    # app_store_connect_api_key(
    #   key_id: "DW9C8JLCRK",
    #   # issuer_id: "6053b7fe-68a8-4acb-89be-165aa6465141",
    #   key_content: ENV['APPSTORE_KEY_PRIVATE'], #"./AuthKey_DW9C8JLCRK.p8",
    #   duration: 1200, # optional (maximum 1200)
    #   in_house: false # optional but may be required if using match/sigh
    # )
  end
  desc "Alias for signing"
  lane :sign do
    signing
  end
  desc "Sync signing"
  lane :signing do
    setup_ci if ENV['CI']
    match(type: "adhoc" , readonly: is_ci)
    match(type: "appstore" , readonly: is_ci)

    mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end
  desc "build ios app"
  lane :build do
    signing
    build_ios_app
  end
  desc "publish"
  lane :publish do
    build
    # upload_to_testflight(skip_waiting_for_build_processing: true)
    # upload_to_app_store # deliver
  end
end
