// en.ts
const messages: Record<string, string> = {
    join_CameraPreviewFallback_allowMediaPermissions: "Allow media device permissions",
    join_PermissionAlertDialog_DialogTitle: "Allow to use your media device for Kidsloop Live",
    join_PermissionAlertDialog_DialogContentText_live: "Kidsloop Live needs access to the camera and microphone in order for other class participants to see you and hear you.",
    join_PermissionAlertDialog_DialogContentText_classes_study: "Kidsloop Live needs access to the microphone for in-class interactive contents.",
    join_PermissionAlertDialog_Button_close: "Close",

    button_submit: "Submit",
    button_close: "Close",
    button_add_comment: "Add comment",
    button_edit_comment: "Edit comment",
    button_file: "File",
    button_camera: "Camera",
    button_gallery: "Gallery",
    button_save: "Save",
    button_continue: "Continue",
    button_ok: "Ok",
    button_delete: "Delete",
    label_not_defined: "Not defined",
    close_confirm_description_1: "Would you like to close the window?",
    close_confirm_description_2: "It will dismiss your change.",
    submission_failed: "Submission Failed",
    upload_please_check_your_file: "Please Check Your File!",
    upload_file_not_supported: "This file format is not supported. Please try another file.",
    upload_file_too_big: "Uploaded file should not be bigger than 100MB. Please try another file.",
    confirm_delete_description: "Are you sure you want to Delete?",
    home_fun_study: "Home Fun Study",

    err_button_home: "Home",
    err_button_signin: "Back to Sign In",
    err_button_confirm: "Comfirm",
    err_400_title: "Bad Request",
    err_400_subtitle: "The server could not understand the request due to invalid syntax",
    err_401_title: "Unauthorized",
    err_401_subtitle: "Please check if you are signed in",
    err_403_title: "Forbidden",
    err_403_title_not_supported: "Not Supported",
    err_403x01_title: "Access Restricted",
    err_403x02_title: "Students Only",
    err_403_subtitle: "You don't have permission to access",
    err_403_subtitle_not_supported: "You have to belong to at least 1 organization",
    err_403_description_not_supported: "The Organization can be invited by your teacher. Also, teacher is not allowed to use Student App. Please use the web browser to start a live as a teacher account.",
    err_403x01_subtitle: "You don't have permission to access. Please check your credentials and try again.",
    err_403x02_subtitle: "You don't have permission to access. Please check your credentials and try again.",
    err_404_title: "Not Found",
    err_404_subtitle: "The requested URL was not found",
    err_500_title: "Internal Server Error",
    err_500_subtitle: "Oops! Something went wrong",

    activity_link: "Activity Link",

    join_live: "Joining Live...",
    join_cameraPreviewFallback_allowMediaPermissions: "Allow media device permissions",
    join_permissionAlertDialog_title: "Allow to use your media device for Kidsloop Live",
    join_permissionAlertDialog_contentText_live: "Kidsloop Live needs access to the camera and microphone in order for other class participants to see you and hear you.",
    join_permissionAlertDialog_contentText_classesStudy: "Kidsloop Live needs access to the microphone for in-class interactive contents.",
    join_permissionAlertDialog_action_close: "Close",

    camera_participantInfo_chalkboardIcon_tooltip: "{name} is teacher",
    camera_participantInfo_crownIcon_tooltip: "Teacher {name} is presenting",
    camera_fullScreenCameraButton_tooltip: "Full screen camera",
    camera_moreControlsButton_listSubheader_whiteboard: "Give Whiteboard Controls",
    camera_moreControlsButton_listSubheader_trophy: "Give Trophy",
    camera_moreControlsButton_listSubheader_toggleCamMic: "Toggle Camera / Microphone",

    whiteboard_permissionControls_listItemText_disallow: "Disallow drawing",
    whiteboard_permissionControls_listItemText_allow: "Allow drawing",
    whiteboard_permissionControls_listItemText_clear: "Clear",

    allow_media_permission: "Please allow microphone and camera permissions if you want to use media devices.",
    button_cancel: "Cancel",
    button_confirm: "Confirm",
    error_camera_unavailable: "Can not access your 📷",
    error_empty_name: "Please enter your name.",
    error_invaild_token: "Invalid token could not connect to class.",
    error_webrtc_unavailable: "Error: WebRTC context unavailable",
    error_unknown_content: "Error: Unknown content type",
    error_unknown_error: "Oops! Something went wrong.",
    error_unknown_user: "Unknown user",
    failed_to_connect: "Failed to connect.",
    hello: "Hello {name}!",
    waiting_for_class: "Waiting for class to start.",
    what_is_your_name: "What is your name?",
    loading: "Loading",
    loading_text: "Give us a sec while we get things ready!",
    student_stream_mode: "Your teacher is currently presenting.",
    student_activity_mode: "Please follow your teacher's intruction.",
    join_room: "Join Room",
    no_device_available: "No devices available",
    no_messages: "No messages yet...",
    no_participants: "No one has join the class yet...",
    select_device: "Select {device}",
    connect_camera: "Connect your 📷",

    refresh_activity: "Refresh Activity",
    what_is_this: "What is This?",
    live_buttonStop: "Stop",
    live_buttonPresent: "Present",
    live_buttonObserve: "Observe",
    live_buttonScreen: "Share Screen",
    live_buttonStopFull: "Webcam Mode",
    live_buttonPresentFull: "Presenter Mode",
    live_buttonObserveFull: "Observation Mode",
    live_buttonScreenFull: "Share Screen",
    title_participants: "Participants",
    title_lesson_plan: "Lesson Plan",
    title_chat: "Chat",
    title_whiteboard: "Whiteboard",
    title_settings: "Settings",
    title_end_class: "End Class",
    end_class_title: "End the class?",
    invite_students: "Invite",
    copy_clipboard: "Copied to clipboard!",
    quick_toggles: "Quick Toggles",
    set_cameras_off: "Set All Cameras Off",
    set_cameras_on: "Set All Cameras On",
    mute_all: "Mute All",
    unmute_all: "Unmute All",
    hide_whiteboard: "Hide All Whiteboards",
    show_whiteboard: "Show All Whiteboards",
    clear_whiteboard: "Clear All Whiteboards",
    give_star: "Give Star to all",
    give_trophy: "Give Trophy to all",
    give_heart: "Give Heart to all",
    encourage: "Encourage to all",
    share_something_here: "Share something here",
    enable_dark_mode: "Enable dark mode",
    language: "Language",
    two_columns: "2 columns",
    three_columns: "3 columns",
    four_columns: "4 columns",
    six_columns: "6 columns",
    cols_camera_per_row: "# of cameras per row",
    cols_observe_per_row: "# of student views per row",

    whiteboard_color: "Color",
    whiteboard_clear: "Clear",
    whiteboard_hide: "Hide",
    whiteboard_show: "Show",

    turn_off_camera: "Turn off camera",
    turn_on_camera: "Turn on camera",
    turn_off_mic: "Turn off microphone",
    turn_on_mic: "Turn on microphone",

    browser_guide_title: "Kidsloop Live supports Chrome only.",
    browser_guide_title_macos: "Kidsloop Live supports Safari and Chrome only on Mac OS.",
    browser_guide_title_ios: "Kidsloop Live supports Safari only on iOS.",
    browser_guide_body: "Please download a supported browser and try again.",

    account_selectOrg_privacyPolicy: "Privacy Policy",
    account_selectOrg_signOut: "Sign Out",
    account_selectOrg_whichOrg: "Select an Organization",
    account_selectUser_whichUser: "Select a Profile",

    schedule_liveTab: "Live",
    schedule_studyTab: "Study",
    schedule_loadingSelectOrg: "Please select an organization first by tapping the top-left corner!",
    schedule_errorFetchTimeViews: "Oops, Failed to load schedules. Retry by tapping refresh button on the top-right corner!",
    schedule_liveSubheaderToday: "TODAY",
    schedule_liveSubheaderTomorrow: "TOMORROW",
    schedule_liveSubheaderUpcoming: "SCHEDULED LIVES",
    schedule_liveNoSchedule: "Nothing scheduled Live",
    schedule_studyAnytimeStudy: "Anytime Study",
    schedule_studyHomeFunStudy: "Home Fun Study",
    schedule_studySubmittedFeedback: "Submitted",
    schedule_studyNoSchedule: "Nothing scheduled Study",
    schedule_selectOrgLoaded: "Please select an organization",

    loading_mediaPermission: "Camera and Microphone premissions required. Please grant the permissions and restart application.",

    title_settings_live: "Room Settings",
    layout_tabinnercontent_leaveroom: "Leave Room",

    support_file_info_title: "Info",
    support_file_max_size: "Max: ",
    support_files: "Support files: ",

    home_fun_study_your_task: "Your task",
    home_fun_study_comment: "Comment...",
    home_fun_study_your_comment: "Your Comment",
    home_fun_study_maximum_three_files: "*Maximum three files",
    home_fun_study_maximum_three_files_limited: "*Maximum three files limit has been reached. Delete uploaded file(s) to upload new file” is displayed on the screen",
    submission_successful : "Submission successful",

    auth_waiting_for_authentication: "Waiting for authentication...",

    cordova_loading: "Loading...",
    cordova_permissions_error: "Camera and Microphone premissions required. Please grant the permissions and restart application.",
    auth_waiting: "Waiting for authentication...",
    loading_try_again: "Try again",
};
export default messages;
