// en.ts
const messages: Record<string, string> = {
    activity_link: "Activity Link",

    join_cameraPreviewFallback_allowMediaPermissions: "Allow media device permissions",
    join_permissionAlertDialog_title: "Allow to use your media device for Kidsloop Live",
    join_permissionAlertDialog_contentText_live: "Kidsloop Live needs access to the camera and microphone in order for other class participants to see you and hear you.",
    join_permissionAlertDialog_contentText_classesStudy: "Kidsloop Live needs access to the microphone for in-class interactive contents.",
    join_permissionAlertDialog_action_close: "Close",

    camera_participantInfo_chalkboardIcon_tooltip: "{name} is teacher",
    camera_participantInfo_crownIcon_tooltip: "Teacher {name} is presenting",
    camera_fullScreenCameraButton_tooltip: "Full screen camera",
    camera_moreControlsButton_listSubheader_whiteboard: "Give Whiteboard Controls",
    camera_moreControlsButton_listSubheader_trophy: "Give Trophy",
    camera_moreControlsButton_listSubheader_toggleCamMic: "Toggle Camera / Microphone",

    whiteboard_permissionControls_listItemText_disallow: "Disallow drawing",
    whiteboard_permissionControls_listItemText_allow: "Allow drawing",
    whiteboard_permissionControls_listItemText_clear: "Clear",

    allow_media_permission: "Please allow microphone and camera permissions if you want to use media devices.",
    error_camera_unavailable: "Can not access your 📷",
    error_empty_name: "Please enter your name.",
    error_invaild_token: "Invalid token could not connect to class.",
    error_webrtc_unavailable: "Error: WebRTC context unavailable",
    error_unknown_content: "Error: Unknown content type",
    error_unknown_error: "Oops! Something went wrong.",
    error_unknown_user: "Unknown user",
    failed_to_connect: "Failed to connect.",
    hello: "Hello {name}!",
    waiting_for_class: "Waiting for class to start.",
    what_is_your_name: "What is your name?",
    loading: "Loading",
    loading_text: "Give us a sec while we get things ready!",
    student_stream_mode: "Your teacher is currently presenting.",
    student_activity_mode: "Please follow your teacher's intruction.",
    join_room: "Join Room",
    no_device_available: "No devices available",
    no_messages: "No messages yet...",
    no_participants: "No one has join the class yet...",
    select_device: "Select {device}",
    connect_camera: "Connect your 📷",

    refresh_activity: "Refresh Activity",
    what_is_this: "What is This?",
    live_buttonStop: "Stop",
    live_buttonPresent: "Present",
    live_buttonObserve: "Observe",
    live_buttonScreen: "Share Screen",
    live_buttonStopFull: "Webcam Mode",
    live_buttonPresentFull: "Presenter Mode",
    live_buttonObserveFull: "Observation Mode",
    live_buttonScreenFull: "Share Screen",
    title_participants: "Participants",
    title_lesson_plan: "Lesson Plan",
    title_chat: "Chat",
    title_whiteboard: "Whiteboard",
    title_settings: "Settings",
    invite_students: "Invite",
    copy_clipboard: "Copied to clipboard!",
    quick_toggles: "Quick Toggles",
    set_cameras_off: "Set All Cameras Off",
    set_cameras_on: "Set All Cameras On",
    mute_all: "Mute All",
    unmute_all: "Unmute All",
    hide_whiteboard: "Hide All Whiteboards",
    show_whiteboard: "Show All Whiteboards",
    clear_whiteboard: "Clear All Whiteboards",
    give_star: "Give Star to all",
    give_trophy: "Give Trophy to all",
    give_heart: "Give Heart to all",
    encourage: "Encourage to all",
    share_something_here: "Share something here",
    enable_dark_mode: "Enable dark mode",
    language: "Language",
    two_columns: "2 columns",
    three_columns: "3 columns",
    four_columns: "4 columns",
    six_columns: "6 columns",
    cols_camera_per_row: "# of cameras per row",
    cols_observe_per_row: "# of student views per row",

    whiteboard_color: "Color",
    whiteboard_clear: "Clear",
    whiteboard_hide: "Hide",
    whiteboard_show: "Show",

    turn_off_camera: "Turn off camera",
    turn_on_camera: "Turn on camera",
    turn_off_mic: "Turn off microphone",
    turn_on_mic: "Turn on microphone",

    browser_guide_title: "Kidsloop Live supports Chrome only.",
    browser_guide_title_macos: "Kidsloop Live supports Safari and Chrome only on Mac OS.",
    browser_guide_title_ios: "Kidsloop Live supports Safari only on iOS.",
    browser_guide_body: "Please download a supported browser and try again.",

};
export default messages;