// id.ts
const messages: Record<string, string> = {
    join_CameraPreviewFallback_allowMediaPermissions: "Allow media device permissions",
    join_PermissionAlertDialog_DialogTitle: "Allow to use your media device for Kidsloop Live",
    join_PermissionAlertDialog_DialogContentText_live: "Kidsloop Live needs access to the camera and microphone in order for other class participants to see you and hear you.",
    join_PermissionAlertDialog_DialogContentText_classes_study: "Kidsloop Live needs access to the microphone for in-class interactive contents.",
    join_PermissionAlertDialog_Button_close: "Close",
    
    err_button_home: "Home",
    err_button_signin: "Back to Sign In",
    err_button_confirm: "Comfirm",
    err_400_title: "Bad Request",
    err_400_subtitle: "The server could not understand the request due to invalid syntax",
    err_401_title: "Unauthorized",
    err_401_subtitle: "Please check if you are signed in",
    err_403_title: "Forbidden",
    err_403_title_not_supported: "Not Supported",
    err_403_subtitle: "You don't have permission to access",
    err_403_subtitle_not_supported: "You have to belong to at least 1 organization",
    err_403_description_not_supported: "The Organization can be invited by your teacher. Also, teacher is not allowed to use Student App. Please use the web browser to start a live as a teacher account.",
    err_404_title: "Not Found",
    err_404_subtitle: "The requested URL was not found",
    err_500_title: "Internal Server Error",
    err_500_subtitle: "Oops! Something went wrong",

    activity_link: "link Aktivitas",

    join_live: "Joining Live...",
    join_cameraPreviewFallback_allowMediaPermissions: "Izinkan penggunaan perangkat media",
    join_permissionAlertDialog_title: "Izinkan penggunaan perangkat media untuk KidsLoop Live",
    join_permissionAlertDialog_contentText_live: "KidslLoop Live butuh akses ke kamera dan mikrofon agar partisipan kelas dapat melihat dan mendengar Anda.",
    join_permissionAlertDialog_contentText_classesStudy: "KidsLoop Live butuh akses ke mikrofon untuk konten interaktif di kelas.",
    join_permissionAlertDialog_action_close: "Tutup",

    camera_participantInfo_chalkboardIcon_tooltip: "{name} adalah guru",
    camera_participantInfo_crownIcon_tooltip: "Guru {name} sedang presentasi",
    camera_fullScreenCameraButton_tooltip: "Kamera full screen",
    camera_moreControlsButton_listSubheader_whiteboard: "Beri Kendali Papan Tulis",
    camera_moreControlsButton_listSubheader_trophy: "Beri Piala",
    camera_moreControlsButton_listSubheader_toggleCamMic: "Alihkan Kamera/Mikrofon",

    whiteboard_permissionControls_listItemText_disallow: "Larang menggambar",
    whiteboard_permissionControls_listItemText_allow: "Izinkan menggambar",
    whiteboard_permissionControls_listItemText_clear: "Hapus",

    allow_media_permission: "silahkan izinkan mikrofon dan kamera jika Anda ingin menggunakan perangkat media.",
    button_cancel: "Cancel",
    button_confirm: "Confirm",
    error_camera_unavailable: "Tidak dapat mengakses 📷  Anda",
    error_empty_name: "Silahkan masukan nama anda.",
    error_invaild_token: "Token tidak valid. tidak dapat terhubung ke kelas.",
    error_webrtc_unavailable: "Kesalahan: Konteks WebRTC tidak ada",
    error_unknown_content: "Kesalahan: Jenis konten tidak diketahui",
    error_unknown_error: "Ups! Ada yang salah.",
    error_unknown_user: "Pengguna tidak dikenal",
    failed_to_connect: "Gagal terhubung.",
    hello: "Halo {name}!",
    waiting_for_class: "Menunggu kelas dimulai.",
    what_is_your_name: "Siapa nama kamu?",
    loading: "Memuat",
    loading_text: " Beri kami waktu sebentar, kami sedang menyiapkannya!",
    student_stream_mode: "Guru Anda sedang presentasi.",
    student_activity_mode: "Silakan ikuti instruksi guru Anda.",
    join_room: "Gabung Kelas",
    no_device_available: "Tidak ada perangkat yang tersedia",
    no_messages: "Belum ada pesan...",
    no_participants: "Belum ada yang gabung dengan kelas ..",
    select_device: "pilih {device}",
    connect_camera: "Hubungkan 📷 Anda",

    refresh_activity: "Refresh aktivitas",
    what_is_this: "Apa ini?",
    live_buttonStop: "Berhenti",
    live_buttonPresent: "Menyampaikan",
    live_buttonObserve: "Mengamati",
    live_buttonScreen: "Berbagi Layar",
    live_buttonStopFull: "Mode Webcam",
    live_buttonPresentFull: "Mode Presenter",
    live_buttonObserveFull: "Mode Pengamatan",
    live_buttonScreenFull: "Berbagi Layar",
    title_participants: "Peserta",
    title_lesson_plan: "Rencana pembelajaran",
    title_chat: "obrolan",
    title_whiteboard: "Papan tulis",
    title_settings: "Pengaturan",
    title_end_class: "End Class",
    end_class_title: "End the class?",
    invite_students: "Undang",
    copy_clipboard: "Disalin ke papan klip!",
    quick_toggles: "Pemilihan Cepat.",
    set_cameras_off: "Matikan Semua Kamera",
    set_cameras_on: "Aktifkan Semua Kamera",
    mute_all: "Bisukan Semua.",
    unmute_all: "suarakan semua. ",
    hide_whiteboard: "Sembunyikan semua papan tulis",
    show_whiteboard: "Tampilkan semua papan tulis",
    clear_whiteboard: "Hapus semua papan tulis",
    give_star: "Beri Bintang untuk semua",
    give_trophy: "Berikan piala untuk semua",
    give_heart: "Berikan Hati untuk semua",
    encourage: "Menganjurkan untuk semua",
    share_something_here: "Berbagi sesuatu di sini.",
    enable_dark_mode: "Aktifkan mode gelap",
    language: "Bahasa",
    two_columns: "2 kolom",
    three_columns: "3 kolom",
    four_columns: "4 kolom",
    six_columns: "5 kolom",
    cols_camera_per_row: "# kamera per baris. ",
    cols_observe_per_row: "# tampilan siswa per baris. ",

    whiteboard_color: "Warna",
    whiteboard_clear: "Hapus",
    whiteboard_hide: "Sembunyikan",
    whiteboard_show: "Tunjukkan",

    turn_off_camera: "Matikan kamera",
    turn_on_camera: "Nyalakan kamera",
    turn_off_mic: "Matikan mikropon",
    turn_on_mic: "Nyalakan mikropon",

    browser_guide_title: "Kidsloop Live hanya mendukung Chrome. ",
    browser_guide_title_macos: "Kidsloop Live hanya mendukung Safari dan Chrome di Mac OS. ",
    browser_guide_title_ios: "Kidsloop Live hanya mendukung Safari di iOS. ",
    browser_guide_body: "Unduh dengan browser yang sesuai dan coba lagi.",

    account_selectOrg_privacyPolicy: "Privacy Policy",
    account_selectOrg_signOut: "Sign Out",
    account_selectOrg_whichOrg: "Select an Organization",
    account_selectUser_whichUser: "Select a Profile",

    schedule_liveTab: "Live",
    schedule_studyTab: "Study",
    schedule_loadingSelectOrg: "Please select an organization first by tapping the top-left corner!",
    schedule_errorFetchTimeViews: "Oops, Failed to load schedules. Retry by tapping refresh button on the top-right corner!",
    schedule_liveSubheaderToday: "TODAY",
    schedule_liveSubheaderTomorrow: "TOMORROW",
    schedule_liveSubheaderUpcoming: "SCHEDULED LIVES",
    schedule_liveNoSchedule: "Nothing scheduled Live",
    schedule_studyAnytimeStudy: "Anytime Study",
    schedule_studyNoSchedule: "Nothing scheduled Study",
    schedule_selectOrgLoaded: "Please select an organization",

    loading_mediaPermission: "Camera and Microphone premissions required. Please grant the permissions and restart application.",

    title_settings_live: "Room Settings",
    layout_tabinnercontent_leaveroom: "Leave Room",

    auth_waiting_for_authentication: "Waiting for authentication...",

    cordova_loading: "Loading...",
    cordova_permissions_error: "Camera and Microphone premissions required. Please grant the permissions and restart application."
};
export default messages;