// id.ts
const messages: Record<string, string> = {
    activity_link: `link Aktivitas`,

    join_cameraPreviewFallback_allowMediaPermissions: `Izinkan penggunaan perangkat media`,
    join_permissionAlertDialog_title: `Izinkan penggunaan perangkat media untuk KidsLoop Live`,
    join_permissionAlertDialog_contentText_live: `KidslLoop Live butuh akses ke kamera dan mikrofon agar partisipan kelas dapat melihat dan mendengar Anda.`,
    join_permissionAlertDialog_contentText_classesStudy: `KidsLoop Live butuh akses ke mikrofon untuk konten interaktif di kelas.`,
    join_permissionAlertDialog_action_close: `Tutup`,

    camera_participantInfo_chalkboardIcon_tooltip: `{name} adalah guru`,
    camera_participantInfo_crownIcon_tooltip: `Guru {name} sedang presentasi`,
    camera_fullScreenCameraButton_tooltip: `Kamera full screen`,
    camera_moreControlsButton_listSubheader_whiteboard: `Beri Kendali Papan Tulis`,
    camera_moreControlsButton_listSubheader_trophy: `Beri Piala`,
    camera_moreControlsButton_listSubheader_toggleCamMic: `Alihkan Kamera/Mikrofon`,

    whiteboard_permissionControls_listItemText_disallow: `Larang menggambar`,
    whiteboard_permissionControls_listItemText_allow: `Izinkan menggambar`,
    whiteboard_permissionControls_listItemText_clear: `Hapus`,

    allow_media_permission: `silahkan izinkan mikrofon dan kamera jika Anda ingin menggunakan perangkat media.`,
    error_camera_unavailable: `Tidak dapat mengakses 📷  Anda`,
    error_empty_name: `Silahkan masukan nama anda.`,
    error_invaild_token: `Token tidak valid. tidak dapat terhubung ke kelas.`,
    error_webrtc_unavailable: `Kesalahan: Konteks WebRTC tidak ada`,
    error_unknown_content: `Kesalahan: Jenis konten tidak diketahui`,
    error_unknown_error: `Ups! Ada yang salah.`,
    error_unknown_user: `Pengguna tidak dikenal`,
    failed_to_connect: `Gagal terhubung.`,
    hello: `Halo {name}!`,
    waiting_for_class: `Menunggu kelas dimulai.`,
    what_is_your_name: `Siapa nama kamu?`,
    loading: `Memuat`,
    loading_text: ` Beri kami waktu sebentar, kami sedang menyiapkannya!`,
    student_stream_mode: `Guru Anda sedang presentasi.`,
    student_activity_mode: `Silakan ikuti instruksi guru Anda.`,
    join_room: `Gabung Kelas`,
    no_device_available: `Tidak ada perangkat yang tersedia`,
    no_messages: `Belum ada pesan...`,
    no_participants: `Belum ada yang gabung dengan kelas ..`,
    select_device: `pilih {device}`,
    connect_camera: `Hubungkan 📷 Anda`,

    refresh_activity: `Refresh aktivitas`,
    what_is_this: `Apa ini?`,
    live_buttonStop: `Berhenti`,
    live_buttonPresent: `Menyampaikan`,
    live_buttonObserve: `Mengamati`,
    live_buttonScreen: `Berbagi Layar`,
    live_buttonStopFull: `Mode Webcam`,
    live_buttonPresentFull: `Mode Presenter`,
    live_buttonObserveFull: `Mode Pengamatan`,
    live_buttonScreenFull: `Berbagi Layar`,
    title_participants: `Peserta`,
    title_lesson_plan: `Rencana pembelajaran`,
    title_chat: `obrolan`,
    title_whiteboard: `Papan tulis`,
    title_settings: `Pengaturan`,
    invite_students: `Undang`,
    copy_clipboard: `Disalin ke papan klip!`,
    quick_toggles: `Pemilihan Cepat.`,
    set_cameras_off: `Matikan Semua Kamera`,
    set_cameras_on: `Aktifkan Semua Kamera`,
    mute_all: `Bisukan Semua.`,
    unmute_all: `suarakan semua. `,
    hide_whiteboard: `Sembunyikan semua papan tulis`,
    show_whiteboard: `Tampilkan semua papan tulis`,
    clear_whiteboard: `Hapus semua papan tulis`,
    give_star: `Beri Bintang untuk semua`,
    give_trophy: `Berikan piala untuk semua`,
    give_heart: `Berikan Hati untuk semua`,
    encourage: `Menganjurkan untuk semua`,
    share_something_here: `Berbagi sesuatu di sini.`,
    enable_dark_mode: `Aktifkan mode gelap`,
    language: `Bahasa`,
    two_columns: `2 kolom`,
    three_columns: `3 kolom`,
    four_columns: `4 kolom`,
    six_columns: `5 kolom`,
    cols_camera_per_row: `# kamera per baris. `,
    cols_observe_per_row: `# tampilan siswa per baris. `,

    whiteboard_color: `Warna`,
    whiteboard_clear: `Hapus`,
    whiteboard_hide: `Sembunyikan`,
    whiteboard_show: `Tunjukkan`,

    turn_off_camera: `Matikan kamera`,
    turn_on_camera: `Nyalakan kamera`,
    turn_off_mic: `Matikan mikropon`,
    turn_on_mic: `Nyalakan mikropon`,

    browser_guide_title: `Kidsloop Live hanya mendukung Chrome. `,
    browser_guide_title_macos: `Kidsloop Live hanya mendukung Safari dan Chrome di Mac OS. `,
    browser_guide_title_ios: `Kidsloop Live hanya mendukung Safari di iOS. `,
    browser_guide_body: `Unduh dengan browser yang sesuai dan coba lagi.`,

    toolbar_class_details: `Class Details`,
    toolbar_canvas: `Canvas`,
    toolbar_global_actions: `Global Actions`,
    toolbar_global_actions_turn_on_screenshare: `Turn on screenshare`,
    toolbar_global_actions_turn_of_screenshare: `Turn off screenshare`,
    toolbar_lesson_plan: `Lesson Plan`,
    toolbar_view_modes: `View Modes`,
    toolbar_view_modes_disabled_screenshare: `View modes are not available when screenshare is active`,
    toolbar_chat: `Chat`,
    toolbar_endcall_ask_to_leave: `Ask permission to leave the class`,
    toolbar_microphonelocked: `The teacher has disabled your microphone`,
    toolbar_camera_locked: `The teacher has disabled your camera`,
    classdetails_details: `Class Details`,
    classdetails_class_name: `Class Name`,
    classdetails_lesson_name: `Lesson Name`,
    classdetails_room_id: `Room ID`,
    classdetails_class_type: `Class Type`,
    classdetails_enrolled_participants: `Enrolled Participants`,
    classdetails_program: `Program`,
    classdetails_subject: `Subject`,
    classdetails_lesson_materials: `Lesson Materials`,
    classdetails_start_time: `Start Time`,
    classdetails_end_time: `End Time`,
    classdetails_roster: `Class Roster`,
    classdetails_roster_teachers: `Teachers`,
    classdetails_roster_students: `Students`,
    classdetails_roster_absents: `Absents`,
    viewmodes_on_stage: `On Stage`,
    viewmodes_observe: `Observe`,
    viewmodes_present: `Present`,
    chat_messages: `Messages`,
    chat_messages_write_placeholder: `Write your message`,
    chat_messages_noresults: `No messages`,
    chat_attachments: `Attachments`,
    chat_attachments_download_label: `Download Attachment`,
    chat_attachments_upload: `Upload`,
    chat_attachments_noresults: `No Attachments`,
    lessonplan_content: `Content`,
    lessonplan_content_noresults: `No lesson material`,
    lessonplan_manuals: `Teacher Manuals`,
    lessonplan_manuals_noresults: `No teacher manuals`,
    settings_menu_settings: `Settings`,
    settings_menu_schedule: `Schedule`,
    settings_menu_toolbar: `Toolbar`,
    settings_menu_record: `Record`,
    settings_language_title: `Language`,
    settings_language_select_language: `Select your language`,
    end_class: `End Class`,
    end_class_confirm: `Are you sure to end the class?`,
    end_class_description: `Ending class will close all user sessions`,
    leave_class: `Leave Class`,
    leave_class_description: `Leaving class will end the class session, close your camera and turn off your microphone`,
    feedback_terrible: `Terrible`,
    feedback_bad: `Bad`,
    feedback_okay: `Okay`,
    feedback_good: `Good`,
    feedback_great: `Great`,
    class_ended_title: `Class has ended`,
    class_ended_thanks_for_attending: `Thanks for attending the class`,
    class_ended_you_have_left: `You have left the class`,
    class_ended_return_to_hub: `Return to hub`,
    parents_captcha_title: `Parents only`,
    parents_captcha_description: `To continue, please tap the numbers in ascending order`,
    parents_captcha_error: `Error, please try again`,
    notification_user_sent_message: `New message from: {user}`,
    notification_user_is_pinned: `{user} has been pinned`,
    notification_you_have_controls: `You have teacher controls`,
    notification_you_dont_have_controls: `You dont' have teacher controls`,
    notification_user_left: `{user} has left the class rooom`,
    notification_user_muted_microphone: `{user} has toggled off their microphone`,
    notification_user_muted_camera: `{user} has toggled off their camera`,
    notification_self_muted_user_microphone: `You have toggled off {user}'s microphone`,
    notification_self_muted_user_camera: `You have toggled off {user}'s camera`,
    notification_self_muted_user_canvas: `You have toggled off {user}'s canvas`,
    notification_self_muted_by_user_microphone: `{user} has toggled off your microphone`,
    notification_self_muted_by_user_camera: `{user} has toggled off your camera`,
    notification_self_muted_by_user_canvas: `{user} has toggled off your canvas`,
    notification_global_mute_microphone: `All student microphones have been toggled off`,
    notification_global_mute_camera: `All student cameras have been toggled off`,
    notification_global_mute_canvas: `All student canvas have been toggled off`,
    notification_global_unmute_microphone: `You can toggle on your microphone`,
    notification_global_unmute_camera: `You can toggle on your camera`,
    notification_new_attachment: `New attachment available`,
    notification_observe_content_interactive: `Content is now interactive`,
    toggle_camera_off: `Toggle camera off`,
    toggle_camera_on: `Toggle camera on`,
    toggle_all_cameras_off: `Toggle all cameras off`,
    toggle_all_cameras_on: `Toggle all cameras on`,
    toggle_microphone_on: `Toggle microphone on`,
    toggle_microphone_off: `Toggle microphone off`,
    toggle_all_microphones_off: `Toggle all microphones off`,
    toggle_all_microphones_on: `Toggle all microphones on`,
    toggle_all_canvas_off: `Toggle all canvas off`,
    toggle_all_canvas_on: `Toggle all canvas on`,
    toggle_room_controls: `Give room controls`,
    common_feature_not_available: `This feature is not available yet`,
    common_close_tab: `Close this tab`,
    common_cancel: `Cancel`,
    common_dismiss: `Dismiss`,
    common_submit: `Submit`,
    title_mosaic: `Mosaic (Press 'esc' to exit)`,
    you: `You`,

    classtype_live: `Online`,
    class_ended_how_was_the_class: `How was the class?`,
    whiteboard_eraser: `Eraser`,
    whiteboard_clear_canvas: `Clear canvas`,
    whiteboard_clear_all_canvas: `Clear all canvas`,
};
export default messages;
