// id.ts
const messages: Record<string, string> = {
    err_button_home: "Home",
    err_button_signin: "Back to Sign In",
    err_button_confirm: "Comfirm",
    err_400_title: "Bad Request",
    err_400_subtitle: "The server could not understand the request due to invalid syntax",
    err_401_title: "Unauthorized",
    err_401_subtitle: "Please check if you are signed in",
    err_403_title: "Forbidden",
    err_403_title_not_supported: "Not Supported",
    err_403_subtitle: "You don't have permission to access",
    err_403_subtitle_not_supported: "You have to belong to at least 1 organization",
    err_403_description_not_supported: "The Organization can be invited by your teacher. Also, teacher is not allowed to use Student App. Please use the web browser to start a live as a teacher account.",
    err_404_title: "Not Found",
    err_404_subtitle: "The requested URL was not found",
    err_500_title: "Internal Server Error",
    err_500_subtitle: "Oops! Something went wrong",

    selectOrg_title: "Which Organization?",
    selectOrg_buttonSelect: "Select",

    activity_link: "link Aktivitas",
    allow_media_permission: "silahkan izinkan mikrofon dan kamera jika Anda ingin menggunakan perangkat media.",
    button_cancel: "Cancel",
    button_confirm: "Confirm",
    error_camera_unavailable: "Tidak dapat mengakses 📷  Anda",
    error_empty_name: "Silahkan masukan nama anda.",
    error_invaild_token: "Token tidak valid. tidak dapat terhubung ke kelas.",
    error_webrtc_unavailable: "Kesalahan: Konteks WebRTC tidak ada",
    error_unknown_content: "Kesalahan: Jenis konten tidak diketahui",
    error_unknown_error: "Ups! Ada yang salah.",
    error_unknown_user: "Pengguna tidak dikenal",
    failed_to_connect: "Gagal terhubung.",
    hello: "Halo (nama)!",
    waiting_for_class: "Menunggu kelas dimulai.",
    what_is_your_name: "Siapa nama kamu?",
    loading: "Memuat",
    loading_text: " Beri kami waktu sebentar, kami sedang menyiapkannya!",
    student_stream_mode: "Guru Anda sedang presentasi.",
    student_activity_mode: "Silakan ikuti instruksi guru Anda.",
    join_room: "Gabung Kelas",
    no_device_available: "Tidak ada perangkat yang tersedia",
    no_messages: "Belum ada pesan...",
    no_participants: "Belum ada yang gabung dengan kelas ..",
    select_device: "pilih (perangkat)",
    connect_camera: "Hubungkan 📷 Anda",

    refresh_activity: "refresh aktivitas",
    what_is_this: "apa ini?",
    live_buttonStop: "Berhenti",
    live_buttonPresent: "menyampaikan",
    live_buttonObserve: "Mengamati",
    live_buttonScreen: "Berbagi Layar",
    live_buttonStopFull: "Mode Webcam",
    live_buttonPresentFull: "Mode Presenter",
    live_buttonObserveFull: "Mode Pengamatan",
    live_buttonScreenFull: "Berbagi Layar",
    title_participants: "Peserta",
    title_lesson_plan: "Rencana pembelajaran",
    title_chat: "obrolan",
    title_whiteboard: "Papan tulis",
    title_settings: "Pengaturan",
    title_end_class: "End Class",
    end_class_title: "End the class?",
    invite_students: "Undang",
    copy_clipboard: "Disalin ke papan klip!",
    quick_toggles: "Pemilihan Cepat.",
    set_cameras_off: "Matikan Semua Kamera",
    set_cameras_on: "aktifkan Semua Kamera",
    mute_all: "Bisukan Semua.",
    unmute_all: "suarakan semua. ",
    hide_whiteboard: "sembunyikan semua papan tulis",
    show_whiteboard: "tampilkan semua papan tulis",
    clear_whiteboard: "hapus semua papan tulis",
    give_star: "Beri Bintang untuk semua",
    give_trophy: "Berikan piala untuk semua",
    give_heart: "Berikan Hati untuk semua",
    encourage: "menganjurkan untuk semua",
    share_something_here: "Berbagi sesuatu di sini.",
    enable_dark_mode: "Aktifkan mode gelap",
    language: "Bahasa",
    two_columns: "2 kolom",
    three_columns: "3 kolom",
    four_columns: "4 kolom",
    six_columns: "5 kolom",
    cols_camera_per_row: "# kamera per baris. ",
    cols_observe_per_row: "# tampilan siswa per baris. ",

    whiteboard_color: "warna",
    whiteboard_clear: "hapus",
    whiteboard_hide: "sembunyikan",
    whiteboard_show: "Tunjukkan",

    turn_off_camera: "matikan kamera",
    turn_on_camera: "nyalakan kamera",
    turn_off_mic: "matikan mikropon",
    turn_on_mic: "nyalakan mikropon",

    browser_guide_title: "Kidsloop Live hanya mendukung Chrome. ",
    browser_guide_title_macos: "Kidsloop Live hanya mendukung Safari dan Chrome di Mac OS. ",
    browser_guide_title_ios: "Kidsloop Live hanya mendukung Safari di iOS. ",
    browser_guide_body: "Unduh dengan browser yang sesuai dan coba lagi..",

};
export default messages;