// ko.ts
const messages: Record<string, string> = {
    err_button_home: "홈",
    err_button_signin: "로그인으로 돌아가기",
    err_button_confirm: "확인",
    err_400_title: "Bad Request",
    err_400_subtitle: "잘못된 요청으로 인해 서버가 처리할 수 없습니다",
    err_401_title: "Unauthorized",
    err_401_subtitle: "로그인된 상태인지 확인해 주세요",
    err_403_title: "Forbidden",
    err_403_title_not_supported: "지원하지 않는 계정",
    err_403_subtitle: "접근 권한이 없습니다",
    err_403_subtitle_not_supported: "적어도 한 개 이상의 기관에 소속되어 있어야 합니다",
    err_403_description_not_supported: "기관은 선생님으로부터 초대받을 수 있습니다. 또한, 선생님은 학생용 앱을 이용할 수 없습니다. 교사 계정으로 수업을 시작하려면 웹 브라우저를 이용하십시오.",
    err_404_title: "Not Found",
    err_404_subtitle: "요청한 URL을 찾을 수 없습니다",
    err_500_title: "Internal Server Error",
    err_500_subtitle: "알 수 없는 문제가 발생했습니다",

    activity_link: "액티비티 링크",
    allow_media_permission: "미디어 장치를 사용하려면 마이크 및 카메라 권한을 허용하십시오.",
    button_cancel: "취소",
    button_confirm: "확인",
    error_camera_unavailable: "📷에 액세스 할 수 없습니다.",
    error_empty_name: "이름을 입력하십시오.",
    error_invaild_token: "권한이 없으므로 수업에 참여할 수 없습니다.",
    error_webrtc_unavailable: "Error : WebRTC 컨텍스트를 사용할 수 없습니다.",
    error_unknown_content: "Error: 콘텐츠 유형을 알 수 없습니다.",
    error_unknown_error: "죄송합니다! 문제가 발생했습니다.",
    error_unknown_user: "알 수 없는 유저",
    failed_to_connect: "연결에 실패했습니다.",
    hello: "안녕, {name}!",
    waiting_for_class: "수업 시작을 기다리는 중입니다.",
    what_is_your_name: "이름이 무엇입니까?",
    loading: "로딩중",
    loading_text: "준비하는 동안 잠시만 기다려주세요!",
    student_stream_mode: "현재 선생님이 수업을 진행하고 있습니다.",
    student_activity_mode: "선생님의 지시에 따르십시오.",
    join_room: "수업 참여",
    no_device_available: "사용 가능한 장치가 없습니다.",
    no_messages: "아직 메시지가 없습니다...",
    no_participants: "아직 수업에 참여한 사람이 없습니다...",
    select_device: "{device} 선택",
    connect_camera: "📷를 연결하십시오.",

    refresh_activity: "액티비티 새로고침",
    what_is_this: "이건 어떤 기능인가요?",
    live_buttonStop: "정지",
    live_buttonPresent: "수업 진행",
    live_buttonObserve: "관찰",
    live_buttonScreen: "화면 공유",
    live_buttonStopFull: "웹캠 모드",
    live_buttonPresentFull: "발표자 모드",
    live_buttonObserveFull: "관찰 모드",
    live_buttonScreenFull: "화면 공유",
    title_participants: "수업 참가자",
    title_lesson_plan: "수업 계획",
    title_chat: "채팅",
    title_whiteboard: "화이트보드",
    title_settings: "설정",
    title_end_class: "수업 종료",
    end_class_title: "수업을 종료 하시겠습니까?",
    invite_students: "초대",
    copy_clipboard: "클립 보드에 복사했습니다!",
    quick_toggles: "빠른 조작",
    set_cameras_off: "카메라 모두 끄기",
    set_cameras_on: "카메라 모두 켜기",
    mute_all: "모두 음소거",
    unmute_all: "모두 음소거 해제",
    hide_whiteboard: "모든 화이트보드 숨기기",
    show_whiteboard: "모든 화이트보드 보이기",
    clear_whiteboard: "모든 화이트보드 지우기",
    give_star: "모두에게 별 주기",
    give_trophy: "모두에게 트로피 주기",
    give_heart: "모두에게 하트 주기",
    encourage: "모두에게 격려하기",
    share_something_here: "공유하고 싶은 것을 올려보세요",
    enable_dark_mode: "다크 모드 켜기",
    language: "언어",
    two_columns: "2 개",
    three_columns: "3 개",
    four_columns: "4 개",
    six_columns: "6 개",
    cols_camera_per_row: "한 줄에 표시할 카메라 수",
    cols_observe_per_row: "한 줄에 표시할 학생 화면 수",

    whiteboard_color: "색깔",
    whiteboard_clear: "지우기",
    whiteboard_hide: "숨기기",
    whiteboard_show: "보기",

    turn_off_camera: "카메라 끄기",
    turn_on_camera: "카메라 켜기",
    turn_off_mic: "마이크 끄기",
    turn_on_mic: "마이크 켜기",

    browser_guide_title: "Kidsloop Live는 Chrome 브라우저만을 지원합니다.",
    browser_guide_title_macos: "Kidsloop Live는 Mac OS에서 Safari와 Chrome 브라우저를 지원합니다.",
    browser_guide_title_ios: "Kidsloop Live는 iOS에서 Safari 브라우저만을 지원합니다.",
    browser_guide_body: "지원하는 브라우저를 다운로드 받고 다시 시도해 주세요.",

    account_selectOrg_privacyPolicy: "개인 정보 정책",
    account_selectOrg_signOut: "로그아웃",
    account_selectOrg_whichOrg: "어떤 기관인가요?",

    schedule_liveTab: "라이브",
    schedule_studyTab: "학습",
    schedule_loadingSelectOrg: "먼저 왼쪽 상단 버튼을 탭하여 기관을 선택하세요!",
    schedule_errorFetchTimeViews: "이런! 스케줄을 불러오지 못했어요. 오른쪽 상단의 새로 고침 버튼을 탭하여 재시도 해보세요!",
    schedule_liveSubheaderToday: "오늘",
    schedule_liveSubheaderTomorrow: "내일",
    schedule_liveSubheaderUpcoming: "예정된 라이브",
    schedule_liveNoSchedule: "아직 스케줄이 없어요",
    schedule_studyAnytimeStudy: "언제나 학습하기",
    schedule_studyNoSchedule: "아직 스케줄이 없어요",

    loading_mediaPermission: "앱을 사용하려면 카메라 및 마이크 권한이 필요해요. 권한을 허용하고 다시 시작해 보세요.",

    title_settings_live: "Room Settings",
    layout_tabinnercontent_leaveroom: "Leave Room"
};
export default messages;