// vi.ts
const messages: Record<string, string> = {
    join_cameraPreviewFallback_allowMediaPermissions: "Allow media device permissions",
    join_permissionAlertDialog_title: "Allow to use your media device for Kidsloop Live",
    join_permissionAlertDialog_contentText_live: "Kidsloop Live needs access to the camera and microphone in order for other class participants to see you and hear you.",
    join_permissionAlertDialog_contentText_classesStudy: "Kidsloop Live needs access to the microphone for in-class interactive contents.",
    join_permissionAlertDialog_action_close: "Close",

    camera_participantInfo_chalkboardIcon_tooltip: "{name} is teacher",
    camera_participantInfo_crownIcon_tooltip: "Teacher {name} is presenting",
    camera_fullScreenCameraButton_tooltip: "Full screen camera",
    camera_moreControlsButton_listSubheader_whiteboard: "Give Whiteboard Controls",
    camera_moreControlsButton_listSubheader_trophy: "Give Trophy",
    camera_moreControlsButton_listSubheader_toggleCamMic: "Toggle Camera / Microphone",

    whiteboard_permissionControls_listItemText_disallow: "Disallow drawing",
    whiteboard_permissionControls_listItemText_allow: "Allow drawing",
    whiteboard_permissionControls_listItemText_clear: "Clear",

    activity_link: "Đường dẫn đến Hoạt động",
    allow_media_permission: "Nếu bạn muốn sử dụng các thiết bị truyền thông, vui lòng cho phép sử dụng micrô và máy ảnh của bạn.",
    error_camera_unavailable: "Không thể truy cập 📷",
    error_empty_name: "Vui lòng nhập tên.",
    error_invaild_token: "Không được cấp phép nên không thể tham gia lớp học.",
    error_webrtc_unavailable: "Lỗi: Không có ngữ cảnh WebRTC",
    error_unknown_content: "Lỗi: Loại nội dung không xác định",
    error_unknown_error: "Tiếc quá! Có lỗi xảy ra.",
    error_unknown_user: "Người dùng không xác định",
    failed_to_connect: "Kết nối thất bại.",
    hello: "Xin chào {name}!",
    waiting_for_class: "Chờ lớp học bắt đầu.",
    what_is_your_name: "Bạn tên gì?",
    loading: "Vui lòng chờ trong giây lát!",
    loading_text: "Vui lòng chờ trong giây lát!",
    student_stream_mode: "Giáo viên của bạn đang trình bày.",
    student_activity_mode: "Vui lòng làm theo hướng dẫn của giáo viên.",
    join_room: "Vào lớp",
    no_device_available: "Không có thiết bị",
    no_messages: "Hiện tại chưa có thông tin...",
    no_participants: "Chưa có ai vào lớp",
    select_device: "Chọn {device}",
    connect_camera: "Kết nối 📷",

    refresh_activity: "Làm mới Hoạt động",
    what_is_this: "Cái gì đây?",
    live_buttonStop: "Ngưng",
    live_buttonPresent: "Trình bày",
    live_buttonObserve: "Chế độ học sinh",
    live_buttonScreen: "Chia sẻ màn hình",
    live_buttonStopFull: "Chế Độ Webcam",
    live_buttonPresentFull: "Chế Độ Trình Chiếu",
    live_buttonObserveFull: "Chế Độ Xem",
    live_buttonScreenFull: "Chế Độ Chia Sẻ Màn Hình",
    title_participants: "Những người tham gia",
    title_lesson_plan: "Giáo án",
    title_chat: "Trò chuyện",
    title_whiteboard: "Bảng",
    title_settings: "Cài đặt",
    invite_students: "Mời",
    copy_clipboard: "Sao chép vào bảng tạm!",
    quick_toggles: "Chuyển đổi nhanh",
    set_cameras_off: "Tắt máy ảnh",
    set_cameras_on: "Bật máy ảnh",
    mute_all: "Tắt tiếng",
    unmute_all: "Bật tiếng",
    hide_whiteboard: "Ẩn Toàn Bộ Bảng",
    show_whiteboard: "Hiện Toàn Bộ Bảng",
    clear_whiteboard: "Xóa Toàn Bộ Bảng",
    give_star: "Gửi Sao tới toàn bộ",
    give_trophy: "Gửi Cúp tới toàn bộ",
    give_heart: "Gửi Tim tới toàn bộ",
    encourage: "Khuyến khích tất cả",
    share_something_here: "Trò chuyện tại đây",
    enable_dark_mode: "Bật chế độ nền tối",
    language: "Ngôn ngữ",
    two_columns: "2 cột",
    three_columns: "3 cột",
    four_columns: "4 cột",
    six_columns: "6 cột",
    cols_camera_per_row: "# Camera mỗi hàng",
    cols_observe_per_row: "Số lượng màn hình học viên được hiển thị trên một hàng",

    whiteboard_color: "Màu",
    whiteboard_clear: "Xóa",
    whiteboard_hide: "Ẩn",
    whiteboard_show: "Hiện",

    turn_off_camera: "Tắt camera",
    turn_on_camera: "Bật camera",
    turn_off_mic: "Tắt tiếng",
    turn_on_mic: "Bật tiếng",

    browser_guide_title: "Kidsloop Live chỉ hỗ trợ trình duyệt Chrome",
    browser_guide_title_macos: "Kidsloop Live chỉ hỗ trợ trình duyệt Chrome và Safari trên máy Mac",
    browser_guide_title_ios: "Kidsloop Live chỉ hỗ trợ Safari cho IOS",
    browser_guide_body: "Xin hãy download trình duyệt được hỗ trợ và thử lại",

};
export default messages;