// vi.ts
const messages: Record<string, string> = {
    activity_link: `Đường dẫn đến Hoạt động`,

    join_cameraPreviewFallback_allowMediaPermissions: `Cho phép truy máy ảnh`,
    join_permissionAlertDialog_title: `Cho phép KidsLoop Live truy cập phương tiện truyền thông của bạn`,
    join_permissionAlertDialog_contentText_live: `Kidsloop Live cần truy cập vào máy ảnh và micrô để những người tham gia lớp học khác có thể nhìn thấy bạn và nghe thấy bạn.`,
    join_permissionAlertDialog_contentText_classesStudy: `Kidsloop Live cần truy cập vào micrô cho nội dung của lớp học tương tác`,
    join_permissionAlertDialog_action_close: `Đóng`,

    camera_participantInfo_chalkboardIcon_tooltip: `{tên} là giáo viên`,
    camera_participantInfo_crownIcon_tooltip: `Giáo viên {tên} đang có mặt`,
    camera_fullScreenCameraButton_tooltip: `Toàn màn hình`,
    camera_moreControlsButton_listSubheader_whiteboard: `Cho phép sử dụng bảng trắng`,
    camera_moreControlsButton_listSubheader_trophy: `Trao cúp thưởng`,
    camera_moreControlsButton_listSubheader_toggleCamMic: `Chuyển đổi máy ảnh / micrô`,

    whiteboard_permissionControls_listItemText_disallow: `Không cho phép vẽ`,
    whiteboard_permissionControls_listItemText_allow: `Cho phép vẽ`,
    whiteboard_permissionControls_listItemText_clear: `Xóa`,

    allow_media_permission: `Nếu bạn muốn sử dụng các thiết bị truyền thông, vui lòng cho phép sử dụng micrô và máy ảnh của bạn.`,
    error_camera_unavailable: `Không thể truy cập 📷`,
    error_empty_name: `Vui lòng nhập tên.`,
    error_invaild_token: `Không được cấp phép nên không thể tham gia lớp học.`,
    error_webrtc_unavailable: `Lỗi: Không có ngữ cảnh WebRTC`,
    error_unknown_content: `Lỗi: Loại nội dung không xác định`,
    error_unknown_error: `Tiếc quá! Có lỗi xảy ra.`,
    error_unknown_user: `Người dùng không xác định`,
    failed_to_connect: `Kết nối thất bại.`,
    hello: `Xin chào {name}!`,
    waiting_for_class: `Chờ lớp học bắt đầu.`,
    what_is_your_name: `Bạn tên gì?`,
    loading: `Vui lòng chờ trong giây lát!`,
    loading_text: `Vui lòng chờ trong giây lát!`,
    student_stream_mode: `Giáo viên của bạn đang trình bày.`,
    student_activity_mode: `Vui lòng làm theo hướng dẫn của giáo viên.`,
    join_room: `Vào lớp`,
    no_device_available: `Không có thiết bị`,
    no_messages: `Hiện tại chưa có thông tin...`,
    no_participants: `Chưa có ai vào lớp`,
    select_device: `Chọn {device}`,
    connect_camera: `Kết nối 📷`,

    refresh_activity: `Làm mới Hoạt động`,
    what_is_this: `Cái gì đây?`,
    live_buttonStop: `Ngưng`,
    live_buttonPresent: `Trình bày`,
    live_buttonObserve: `Chế độ học sinh`,
    live_buttonScreen: `Chia sẻ màn hình`,
    live_buttonStopFull: `Chế Độ Webcam`,
    live_buttonPresentFull: `Chế Độ Trình Chiếu`,
    live_buttonObserveFull: `Chế Độ Xem`,
    live_buttonScreenFull: `Chế Độ Chia Sẻ Màn Hình`,
    title_participants: `Những người tham gia`,
    title_lesson_plan: `Giáo án`,
    title_chat: `Trò chuyện`,
    title_whiteboard: `Bảng`,
    title_settings: `Cài đặt`,
    invite_students: `Mời`,
    copy_clipboard: `Sao chép vào bảng tạm!`,
    quick_toggles: `Chuyển đổi nhanh`,
    set_cameras_off: `Tắt máy ảnh`,
    set_cameras_on: `Bật máy ảnh`,
    mute_all: `Tắt tiếng`,
    unmute_all: `Bật tiếng`,
    hide_whiteboard: `Ẩn Toàn Bộ Bảng`,
    show_whiteboard: `Hiện Toàn Bộ Bảng`,
    clear_whiteboard: `Xóa Toàn Bộ Bảng`,
    give_star: `Gửi Sao tới toàn bộ`,
    give_trophy: `Gửi Cúp tới toàn bộ`,
    give_heart: `Gửi Tim tới toàn bộ`,
    encourage: `Khuyến khích tất cả`,
    share_something_here: `Trò chuyện tại đây`,
    enable_dark_mode: `Bật chế độ nền tối`,
    language: `Ngôn ngữ`,
    two_columns: `2 cột`,
    three_columns: `3 cột`,
    four_columns: `4 cột`,
    six_columns: `6 cột`,
    cols_camera_per_row: `# Camera mỗi hàng`,
    cols_observe_per_row: `Số lượng màn hình học viên được hiển thị trên một hàng`,

    whiteboard_color: `Màu`,
    whiteboard_clear: `Xóa`,
    whiteboard_hide: `Ẩn`,
    whiteboard_show: `Hiện`,

    turn_off_camera: `Tắt camera`,
    turn_on_camera: `Bật camera`,
    turn_off_mic: `Tắt tiếng`,
    turn_on_mic: `Bật tiếng`,

    browser_guide_title: `Kidsloop Live chỉ hỗ trợ trình duyệt Chrome`,
    browser_guide_title_macos: `Kidsloop Live chỉ hỗ trợ trình duyệt Chrome và Safari trên máy Mac`,
    browser_guide_title_ios: `Kidsloop Live chỉ hỗ trợ Safari cho IOS`,
    browser_guide_body: `Xin hãy download trình duyệt được hỗ trợ và thử lại`,

    toolbar_class_details: `Class Details`,
    toolbar_canvas: `Canvas`,
    toolbar_global_actions: `Global Actions`,
    toolbar_global_actions_turn_on_screenshare: `Turn on screenshare`,
    toolbar_global_actions_turn_of_screenshare: `Turn off screenshare`,
    toolbar_lesson_plan: `Lesson Plan`,
    toolbar_view_modes: `View Modes`,
    toolbar_view_modes_disabled_screenshare: `View modes are not available when screenshare is active`,
    toolbar_chat: `Chat`,
    toolbar_endcall_ask_to_leave: `Ask permission to leave the class`,
    toolbar_microphonelocked: `The teacher has disabled your microphone`,
    toolbar_camera_locked: `The teacher has disabled your camera`,
    classdetails_details: `Class Details`,
    classdetails_class_name: `Class Name`,
    classdetails_lesson_name: `Lesson Name`,
    classdetails_room_id: `Room ID`,
    classdetails_class_type: `Class Type`,
    classdetails_enrolled_participants: `Enrolled Participants`,
    classdetails_program: `Program`,
    classdetails_subject: `Subject`,
    classdetails_lesson_materials: `Lesson Materials`,
    classdetails_start_time: `Start Time`,
    classdetails_end_time: `End Time`,
    classdetails_roster: `Class Roster`,
    classdetails_roster_teachers: `Teachers`,
    classdetails_roster_students: `Students`,
    classdetails_roster_absents: `Absents`,
    viewmodes_on_stage: `On Stage`,
    viewmodes_observe: `Observe`,
    viewmodes_present: `Present`,
    chat_messages: `Messages`,
    chat_messages_write_placeholder: `Write your message`,
    chat_messages_noresults: `No messages`,
    chat_attachments: `Attachments`,
    chat_attachments_download_label: `Download Attachment`,
    chat_attachments_upload: `Upload`,
    chat_attachments_noresults: `No Attachments`,
    lessonplan_content: `Content`,
    lessonplan_content_noresults: `No lesson material`,
    lessonplan_manuals: `Teacher Manuals`,
    lessonplan_manuals_noresults: `No teacher manuals`,
    settings_menu_settings: `Settings`,
    settings_menu_schedule: `Schedule`,
    settings_menu_toolbar: `Toolbar`,
    settings_menu_record: `Record`,
    settings_language_title: `Language`,
    settings_language_select_language: `Select your language`,
    end_class: `End Class`,
    end_class_confirm: `Are you sure to end the class?`,
    end_class_description: `Ending class will close all user sessions`,
    leave_class: `Leave Class`,
    leave_class_description: `Leaving class will end the class session, close your camera and turn off your microphone`,
    feedback_terrible: `Terrible`,
    feedback_bad: `Bad`,
    feedback_okay: `Okay`,
    feedback_good: `Good`,
    feedback_great: `Great`,
    class_ended_title: `Class has ended`,
    class_ended_thanks_for_attending: `Thanks for attending the class`,
    class_ended_you_have_left: `You have left the class`,
    class_ended_return_to_hub: `Return to hub`,
    parents_captcha_title: `Parents only`,
    parents_captcha_description: `To continue, please tap the numbers in ascending order`,
    parents_captcha_error: `Error, please try again`,
    notification_user_sent_message: `New message from: {user}`,
    notification_user_is_pinned: `{user} has been pinned`,
    notification_you_have_controls: `You have teacher controls`,
    notification_you_dont_have_controls: `You dont' have teacher controls`,
    notification_user_left: `{user} has left the class rooom`,
    notification_user_muted_microphone: `{user} has toggled off their microphone`,
    notification_user_muted_camera: `{user} has toggled off their camera`,
    notification_self_muted_user_microphone: `You have toggled off {user}'s microphone`,
    notification_self_muted_user_camera: `You have toggled off {user}'s camera`,
    notification_self_muted_user_canvas: `You have toggled off {user}'s canvas`,
    notification_self_muted_by_user_microphone: `{user} has toggled off your microphone`,
    notification_self_muted_by_user_camera: `{user} has toggled off your camera`,
    notification_self_muted_by_user_canvas: `{user} has toggled off your canvas`,
    notification_global_mute_microphone: `All student microphones have been toggled off`,
    notification_global_mute_camera: `All student cameras have been toggled off`,
    notification_global_mute_canvas: `All student canvas have been toggled off`,
    notification_global_unmute_microphone: `You can toggle on your microphone`,
    notification_global_unmute_camera: `You can toggle on your camera`,
    notification_new_attachment: `New attachment available`,
    notification_observe_content_interactive: `Content is now interactive`,
    toggle_camera_off: `Toggle camera off`,
    toggle_camera_on: `Toggle camera on`,
    toggle_all_cameras_off: `Toggle all cameras off`,
    toggle_all_cameras_on: `Toggle all cameras on`,
    toggle_microphone_on: `Toggle microphone on`,
    toggle_microphone_off: `Toggle microphone off`,
    toggle_all_microphones_off: `Toggle all microphones off`,
    toggle_all_microphones_on: `Toggle all microphones on`,
    toggle_all_canvas_off: `Toggle all canvas off`,
    toggle_all_canvas_on: `Toggle all canvas on`,
    toggle_room_controls: `Give room controls`,
    common_feature_not_available: `This feature is not available yet`,
    common_close_tab: `Close this tab`,
    common_cancel: `Cancel`,
    common_dismiss: `Dismiss`,
    common_submit: `Submit`,
    title_mosaic: `Mosaic (Press 'esc' to exit)`,
    you: `You`,

    classtype_live: `Online`,
    class_ended_how_was_the_class: `How was the class?`,
    whiteboard_eraser: `Eraser`,
    whiteboard_clear_canvas: `Clear canvas`,
    whiteboard_clear_all_canvas: `Clear all canvas`,
};
export default messages;
