// ko.ts
const messages: Record<string, string> = {
    activity_link: "액티비티 링크",
    allow_media_permission: "미디어 장치를 사용하려면 마이크 및 카메라 권한을 허용하십시오.",
    error_camera_unavailable: "📷에 액세스 할 수 없습니다.",
    error_empty_name: "이름을 입력하십시오.",
    error_invaild_token: "권한이 없으므로 수업에 참여할 수 없습니다.",
    error_webrtc_unavailable: "Error : WebRTC 컨텍스트를 사용할 수 없습니다.",
    error_unknown_content: "Error: 콘텐츠 유형을 알 수 없습니다.",
    error_unknown_error: "죄송합니다! 문제가 발생했습니다.",
    error_unknown_user: "알 수 없는 유저",
    failed_to_connect: "연결에 실패했습니다.",
    hello: "안녕, {name}!",
    waiting_for_class: "수업 시작을 기다리는 중입니다.",
    what_is_your_name: "이름이 무엇입니까?",
    loading: "로딩중",
    loading_text: "준비하는 동안 잠시만 기다려주세요!",
    student_stream_mode: "현재 선생님이 수업을 진행하고 있습니다.",
    student_activity_mode: "선생님의 지시에 따르십시오.",
    join_room: "수업 참여",
    no_device_available: "사용 가능한 장치가 없습니다.",
    no_messages: "아직 메시지가 없습니다...",
    no_participants: "아직 수업에 참여한 사람이 없습니다 ...",
    select_device: "{device} 선택",
    connect_camera: "📷를 연결하십시오.",

    refresh_activity: "액티비티 새로고침",
    what_is_this: "이건 어떤 기능인가요?",
    live_buttonStop: "정지",
    live_buttonPresent: "수업 진행",
    live_buttonObserve: "학생 모드",
    live_buttonScreen: "화면 공유",
    live_buttonStopFull: "Webcam Mode",
    live_buttonPresentFull: "Presenter Mode",
    live_buttonObserveFull: "Observation Mode",
    live_buttonScreenFull: "Share Screen",
    title_participants: "수업 참가자",
    title_lesson_plan: "수업 계획",
    title_chat: "채팅",
    title_whiteboard: "화이트보드",
    title_settings: "설정",
    invite_students: "초대",
    copy_clipboard: "클립 보드에 복사했습니다!",
    quick_toggles: "빠른 조작",
    set_cameras_off: "카메라 모두 끄기",
    set_cameras_on: "카메라 모두 켜기",
    clear_whiteboard: "화이트보드 지우기",
    mute_all: "모두 음소거",
    unmute_all: "모두 음소거 해제",
    share_something_here: "공유하고 싶은 것을 올려보세요",
    enable_dark_mode: "다크 모드 켜기",
    language: "언어",
    two_columns: "2 개",
    four_columns: "4 개",
    six_columns: "6 개",
    num_views_per_row: "한 줄에 표시할 학생 화면 수",

    whiteboard_color: "색깔",
    whiteboard_clear: "지우기",
    whiteboard_hide: "숨기기",
    whiteboard_show: "보기",

    turn_off_camera: "카메라 끄기",
    turn_on_camera: "카메라 켜기",
    turn_off_mic: "마이크 끄기",
    turn_on_mic: "마이크 켜기",

    browser_guide_title: "Kidsloop Live는 Chrome 브라우저만을 지원합니다.",
    browser_guide_title_macos: "Kidsloop Live는 Mac OS에서 Safari와 Chrome 브라우저를 지원합니다.",
    browser_guide_title_ios: "Kidsloop Live는 iOS에서 Safari 브라우저만을 지원합니다.",
    browser_guide_body: "지원하는 브라우저를 다운로드 받고 다시 시도해 주세요.",
};
export default messages;