// ko.ts
const messages: Record<string, string> = {
    activity_link: "액티비티 링크",
    allow_media_permission: "미디어 장치를 사용하려면 마이크 및 카메라 권한을 허용하십시오.",
    button_invite_students: "초대",
    error_camera_unavailable: "📷에 액세스 할 수 없습니다.",
    error_empty_name: "이름을 입력하십시오.",
    error_invaild_token: "권한이 없으므로 수업에 참여할 수 없습니다.",
    error_webrtc_unavailable: "Error: WebRTC context unavailable",
    error_unknown_content: "Error: Unknown content type",
    error_unknown_error: "죄송합니다! 문제가 발생했습니다.",
    failed_to_connect: "연결에 실패했습니다.",
    hello: "안녕, {name}!",
    waiting_for_class: "수업 시작을 기다리는 중입니다.",
    what_is_your_name: "이름이 무엇입니까?",
    live_buttonStop: "정지",
    live_buttonScreen: "화면 공유",
    live_buttonPresent: "수업 진행",
    live_buttonActivity: "학생 모드",
    loading: "준비하는 동안 잠시만 기다려주세요!",
    student_stream_mode: "선생님이 현재 수업 진행 중입니다.",
    student_activity_mode: "선생님의 지시에 따르십시오.",
    join_room: "수업 참여",
    no_device_available: "사용 가능한 장치가 없습니다.",
    no_messages: "아직 메시지가 없습니다...",
    select_device: "{device} 선택",
    connect_camera: "📷를 연결하십시오.",

    quick_toggles: "빠른 조작",
    set_cameras_off: "카메라 모두 끄기",
    set_cameras_on: "카메라 모두 켜기",
    mute_all: "모두 음소거",
    unmute_all: "모두 음소거 해제",

    // Whiteboard
    whiteboard_color: "색깔",
    whiteboard_clear: "지우기",
    whiteboard_hide: "숨기기",
    whiteboard_show: "보기",
};
export default messages;
