// vi.ts
const messages: Record<string, string> = {
    activity_link: "Activity Link",
    allow_media_permission: "Please allow microphone and camera permissions if you want to use media devices.",
    error_camera_unavailable: "Can not access your 📷",
    error_empty_name: "Please enter your name.",
    error_invaild_token: "Invalid token, could not connect to class.",
    error_webrtc_unavailable: "Error: WebRTC context unavailable",
    error_unknown_content: "Error: Unknown content type",
    error_unknown_error: "Oops! Something went wrong.",
    failed_to_connect: "Failed to connect.",
    hello: "Hello, {name}!",
    waiting_for_class: "Waiting for class to start.",
    what_is_your_name: "What is your name?",
    loading: "Give us a sec while we get things ready!",
    student_stream_mode: "Your teacher is currently presenting.",
    student_activity_mode: "Please follow your teacher's intruction.",
    join_room: "Join Room",
    no_device_available: "No devices available",
    no_messages: "No messages yet...",
    select_device: "Select {device}",
    connect_camera: "Connect your 📷",

    // Drawer
    refresh_activity: "Refresh Activity",
    what_is_this: "What is This?",
    live_buttonStop: "Stop",
    live_buttonPresent: "Present",
    live_buttonActivity: "Student Mode",
    live_buttonScreen: "Share Screen",
    title_participants: "Participants",
    title_lesson_plan: "Lesson Plan",
    title_chat: "Chat",
    title_whiteboard: "Whiteboard",
    title_settings: "Settings",
    invite_students: "Invite",
    copy_clipboard: "Copied to clipboard!",
    quick_toggles: "Quick Toggles",
    set_cameras_off: "Set Cameras Off",
    set_cameras_on: "Set Cameras On",
    mute_all: "Mute All",
    unmute_all: "Unmute All",
    share_something_here: "Share something here",

    // Whiteboard
    whiteboard_color: "Color",
    whiteboard_clear: "Clear",
    whiteboard_hide: "Hide",
    whiteboard_show: "Show",
};
export default messages;
