// cn.ts
const messages: Record<string, string> = {
    activity_link: "活动链接",
    allow_media_permission: "如果您想要使用媒体设备，请授权允许使用你的话筒和相机",
    error_camera_unavailable: "📷摄像头无法访问",
    error_empty_name: "请输入你的名字",
    error_invaild_token: "没有权限无法上课",
    error_webrtc_unavailable: "错误：WebRTC 上下文不可用",
    error_unknown_content: "错误：未知内容类型",
    error_unknown_error: "对不起！发生了一些错误",
    error_unknown_user: "未知用户",
    failed_to_connect: "连接失败",
    hello: "你好，{name}！",
    waiting_for_class: "等待课程开始",
    what_is_your_name: "你叫什么名字",
    loading: "Loading",
    loading_text: "正在准备请稍等！",
    student_stream_mode: "老师目前正在上课",
    student_activity_mode: "请遵照老师的指示",
    join_room: "进入教室",
    no_device_available: "没有可用的设备",
    no_messages: "目前没有信息...",
    no_participants: "No one has join the class yet...",
    select_device: "选择{device}",
    connect_camera: "访问你的摄像头📷",

    refresh_activity: "刷新活动",
    what_is_this: "这是什么？",
    live_buttonStop: "停止",
    live_buttonPresent: "课程演示",
    live_buttonObserve: "学生模式",
    live_buttonScreen: "共享屏幕",
    title_participants: "参加人员",
    title_lesson_plan: "教学计划",
    title_chat: "聊天",
    title_whiteboard: "白板",
    title_settings: "设置",
    invite_students: "邀请",
    copy_clipboard: "复制到剪贴板",
    quick_toggles: "快速操作",
    set_cameras_off: "设置摄像头关闭",
    set_cameras_on: "设置摄像头打开",
    mute_all: "全部静音",
    unmute_all: "解除静音",
    hide_whiteboard: "Hide Whiteboard",
    show_whiteboard: "Show Whiteboard",
    clear_whiteboard: "Clear Whiteboard",
    give_star: "Give Star to all",
    give_trophy: "Give Trophy to all",
    give_heart: "Give Heart to all",
    encourage: "Encourage to all",
    share_something_here: "上传你想分享的内容",
    enable_dark_mode: "使用深色模式",
    language: "语言",
    two_columns: "2列",
    three_columns: "3列",
    four_columns: "4列",
    six_columns: "6列",
    cols_camera_per_row: "# of cameras per row",
    cols_observe_per_row: "一行中显示的学生屏幕数量",

    whiteboard_color: "颜色",
    whiteboard_clear: "清除",
    whiteboard_hide: "隐藏",
    whiteboard_show: "展示",

    turn_off_camera: "Turn off camera",
    turn_on_camera: "Turn on camera",
    turn_off_mic: "Turn off microphone",
    turn_on_mic: "Turn on microphone",

    browser_guide_title: "Kidsloop Live supports Chrome only.",
    browser_guide_title_macos: "Kidsloop Live supports Safari and Chrome only on Mac OS.",
    browser_guide_title_ios: "Kidsloop Live supports Safari only on iOS.",
    browser_guide_body: "Please download a supported browser and try again.",
};
export default messages;