name: Bump version

on:
    workflow_dispatch:

jobs:
    install:
        uses: ./.github/workflows/install.yml
        secrets:
            NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    generate-version:
        needs: [install]
        uses: ./.github/workflows/generate-version.yml
