# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy to Alpha with New Tag

on:
  push:
    tags:        
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}
      - run: npm ci
      - run: npm test -- --coverage --coverageReporters="text-summary"
  build-and-deploy:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}
      - run: npm ci
      - run: cp deploy/config/internal/.env.alpha ./.env
      - run: npm run build
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID_ALPHA_DEV}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_ALPHA_DEV}}
      - run: pip3 install -U awscli
      - run: aws s3 sync dist s3://kidsloop-alpha-live-crack-drake/
      - run: aws cloudfront create-invalidation --paths "/*" --distribution-id E2694SIA1FLALO
