name: (Job) Generate version

concurrency: 
    group: VersionGeneration
    cancel-in-progress: true

on:
    workflow_call:
        secrets:
            NODE_AUTH_TOKEN:
                required: true

jobs:
    generate-version:
        runs-on: ubuntu-latest
        environment:
            name: alpha-dev
            url: https://hub.alpha.kidsloop.net
        steps:
          - uses: actions/checkout@v2
            with:
                persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          - uses: actions/setup-node@v2
            with:
                node-version: 16
                registry-url: https://npm.pkg.github.com/

          - name: Find node_modules cache
            id: cache-node_modules
            uses: actions/cache@v3
            with:
                path: ./node_modules
                key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

          - name: Setup git user config
            run: |
                git config --global user.email "github-action@kidsloop.live"
                git config --global user.name "GitHub Action"

          - name: Generate version
            run: npm run release

          - name: Push changes
            uses: ad-m/github-push-action@master
            with:
                github_token: ${{ secrets.NODE_AUTH_TOKEN }}
                branch: ${{ github.ref }}
                tags: true
