name: (Job) Generate version

on:
    workflow_call:

jobs:
    generate-version:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
                # persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
                fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          - uses: actions/setup-node@v2
            with:
                node-version: 16
                registry-url: https://npm.pkg.github.com/
            env:
                NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

          - name: Find node_modules cache
            id: cache-node_modules
            uses: actions/cache@v3
            with:
                path: ./node_modules
                key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

          - name: Generate version
            run: npm run release

          - name: Push changes
            uses: ad-m/github-push-action@master
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}
                tags: true
