name: Install dependencies

on:
    workflow_call:

jobs:
    install:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
                node-version: 16
                registry-url: https://npm.pkg.github.com/
            env:
                NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

          - name: Find node_modules cache
            id: cache-node_modules
            uses: actions/cache@v3
            with:
                path: ./node_modules
                key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
                
          - name: Install dependencies
            if: steps.cache-node_modules.outputs.cache-hit != 'true'
            run: npm ci
