name: iOS starter workflow

on:
  push:
    branches: [ "ios-build" ]
  pull_request:
    branches: [ "ios-build" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          token: ${{ secrets.PAT_NPM_GITHUB_REPO }}
      - name: setup ios build
        run: |
          ruby --version
          gem install bundler:1.17.2
          bundle install
      - name: Setup Cordova
        run: |
          sudo npm install -g cordova
          cordova telemetry off
      # - name: Dependencies install and build
      #   # fixes cache issue
      #   # [ $? -ne 0 ] && echo "Failed to build webpack" && exit 1
      #   # sudo rm -rf /Users/runner/.npm/_cacache/*
      #   run: |
      #     npm ci
      #     npm run build:app
      #   env:
      #     NPM_GITHUB_TOKEN: ${{secrets.PAT_NPM_GITHUB_REPO}}
      - name: Prep iOS development
        env:
          ENDPOINT_GQL: "https://live.kidsloop.net/graphql"
          USE_TEST_TOKEN: 1
          WEBRTC_DEVICE_HANDLER_NAME: Safari12
          CUSTOM_UA: cordovaios
          IS_CORDOVA_BUILD: "true"

          NPM_GITHUB_TOKEN: ${{secrets.PAT_NPM_GITHUB_REPO}}
        run: |
          npm ci
          npm run build:app
          ./scripts/parse-cordova-private-plugins.sh          
          cordova prepare ios
          ./scripts/edit-ios-platform.sh

          xcodebuild -list -workspace ./platforms/ios/KidsLoop.xcworkspace
          xcodebuild -list -project ./platforms/ios/KidsLoop.xcodeproj

        # temporarily disable the full cordova emulator build
        # sudo chown -R 501:20 "/Users/runner/.npm"
        # cordova build ios --buildFlag='-UseModernBuildSystem=0'
      - name: fastlane stuff
        env:
          FASTLANE: 1
        run: |
          bundle exec fastlane precheck --verbose
          bundle exec fastlane ios build
          bundle exec fastlane match
      # - name: Archive app build
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: KidsLoop.app
      #     path: ./platforms/ios/build/emulator/KidsLoop.app
      