name: iOS starter workflow

on:
  push:
    branches: [ "ios-build" ]
  pull_request:
    branches: [ "ios-build" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          token: ${{ secrets.PACKAGES_TOKEN }}
          cache: 'npm'
      - name: setup fastlane
        run: |
          ruby --version
          gem install bundler:1.17.2
          bundle install
          bundle info bundler
          bundle info fastlane
          bundle info dotenv
          gem cleanup
      - name: Cache gems
        uses: actions/cache@v2
        env:
          cache-name: cache-ruby-gems
        with:
          path: /usr/local/lib/ruby/gems/2.7.0/gems/
          key: ${{ env.cache-name }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ env.cache-name }}-
      - name: Setup Cordova
        run: |
          sudo npm install -g cordova
          cordova telemetry off
      - name: Prep iOS development
        env:
          ENDPOINT_GQL: "https://live.kidsloop.net/graphql"
          USE_TEST_TOKEN: 1
          WEBRTC_DEVICE_HANDLER_NAME: Safari12
          CUSTOM_UA: cordovaios
          IS_CORDOVA_BUILD: "true"
          NPM_GITHUB_TOKEN: ${{secrets.PACKAGES_TOKEN}}
        run: |
          sudo chown -R 501:20 "/Users/runner/.npm"
          npm ci
          npm run build:app
          ./scripts/parse-cordova-private-plugins.sh
          cordova prepare ios
          ./scripts/edit-ios-platform.sh

          xcodebuild -list -workspace ./platforms/ios/KidsLoop.xcworkspace
          xcodebuild -list -project ./platforms/ios/KidsLoop.xcodeproj

        # temporarily disable the full cordova emulator build
        # cordova build ios --buildFlag='-UseModernBuildSystem=0'
      - name: fastlane stuff
        env:
          FASTLANE: 1
          FASTLANE_DISABLE_COLORS: 1
          FASTLANE_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
          MATCH_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{secrets.APPSTORE_KEY_ID}}
          APP_STORE_CONNECT_API_KEY_KEY: ${{secrets.APPSTORE_KEY_PRIVATE}}
        run: |
          eval $(bundle exec fastlane spaceauth -u build-machine@calmid.com 2>/dev/null | grep "export FASTLANE_SESSION")
          bundle exec fastlane run opt_out_usage
          bundle exec fastlane precheck --verbose
          bundle exec fastlane ios signing
          bundle exec fastlane ios build
          bundle exec fastlane ios publish

# this seems to hang the pipeline
# yes | bundle exec fastlane spaceauth -u build-machine@calmid.com
# export FASTLANE_SESSION=$(pbpaste)