name: (Job) Test (unit)

on:
    workflow_call:

jobs:
    test-unit:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
                node-version: 16
                registry-url: https://npm.pkg.github.com/
                
          - name: Find node_modules cache
            id: cache-node_modules
            uses: actions/cache@v3
            with:
                path: ./node_modules
                key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

          - name: Run tests
            run: npm test -- --coverage --coverageReporters="text-summary"